INSERT INTO QnA(Question_ID, Question_type, Question_Catagory, Question, Answer1, Answer2, Answer3, correct_answer)
VALUES 
(1, 'OPEN', 'Geography', 'Hoe hoog is de Euromast?(Schat tot op 5 meter nauwkeurig.)', NULL, NULL, NULL, '185 meter'),
(2, 'OPEN', 'Geography', 'Welke stad is groter dan Rotterdam?', NULL, NULL, NULL, 'geen'), 
(3, 'OPEN', 'Geography', 'Wat is de hoogste brug van Rotterdam?', NULL, NULL, NULL, 'de erasmusbrug'), 
(4, 'OPEN', 'Geography', 'Hoe groot is Rotterdam, inclusief wateren? (Schat op 50km2 nauwkeurig.)', NULL, NULL, NULL, '319,4 km2'),
(5, 'OPEN', 'Geography', 'Hoe heet de berg die in Rotterdam ligt?', NULL, NULL, NULL, 'rotterdam heeft geen bergen'),
(6, 'OPEN', 'Geography', 'Welke klimaat heerst er in Rotterdam?', NULL, NULL, NULL, 'gematigd zeeklimaat'),
(7, 'OPEN', 'Geography', 'Wat is de oudste deelgemeente van Rotterdam?', NULL, NULL, NULL, 'rotterdam-noord'), 
(8, 'OPEN', 'Geography', 'Hoe heet het monument dat op een kerstboom had moeten lijken.', NULL, NULL, NULL, 'santa claus'),
(9, 'OPEN', 'Geography', 'Welke snel-of-autowegen liggen er langs of door Rotterdam.', NULL, NULL, NULL, 'A13, A15, A16 en de A20'),
(10,'OPEN', 'Geography', 'Hoe heten de bekendste huizen van Rotterdam?', NULL, NULL, NULL, 'de kubuswoningen'),
(11,'OPEN', 'Geography', 'Wat is het hoogste gebouw van Rotterdam?', NULL, NULL, NULL, 'de maastoren met 164,75m'), 
(12,'OPEN', 'Geography', 'Hoeveel autos staan er ongeveer geregistreerd in Rotterdam? (Schat tot op 5000 autos nauwkeurig)', NULL, NULL, NULL, 'ongeveer 200.000 autos'),
(13,'OPEN', 'Geography', 'Noem minimaal 3 deelgemeentes uit Rotterdam.', NULL, NULL, NULL, 'rotterdam centrum, charlois, delfshaven, feijenoord, hillegersberg, schiebroek, hoek van holland, hoogvliet, ijsselmonde, kralingen-crooswijk, noord, overschie, pernis, prins alexander en rozenburg'), 
(14,'OPEN', 'Geography', 'Hoeveel mensen wonen er ongeveer in Rotterdam? (Schat tot op 5000 mensen nauwkeurig', NULL, NULL, NULL, 'ongeveer 610.000'),
(15,'OPEN', 'Geography', 'Hoeveel winkels telt Rotterdam? (Schat tot op 500 winkels nauwkeurig)', NULL, NULL, NULL, 'ongeveer 9455 winkels'), 
(16, 'MC', 'Geography', 'Wat is het belangrijkste vervoersmiddel in Rotterdam?', 'A. Metro', 'B. Auto', 'C. Fiets', 'A'),
(17, 'MC', 'Geography', 'De haven van Rotterdam is grootste haven van Nederland.', 'A. Waar', 'B. Niet Waar', NULL, 'A'),
(18, 'MC', 'Geography', 'Hoe word Rotterdam ook wel genoemd?', 'A. Stad der wonderen', 'B. Stad der steden', 'C. Haven stad', 'C'),
(19, 'MC', 'Geography', 'In welke provincie ligt Rotterdam?', 'A. Noord-Holland', 'B. Zuid-Holland', 'C. Noord-Holland', 'B'),
(20, 'MC', 'Geography', 'Rotterdam is de hoofdstad van Zuid-Holland.', 'A. Waar', 'B. Niet Waar', NULL, 'B'),
(21, 'MC', 'Geography', 'Hoeveel regen valt er gemiddeld per jaar in Rotterdam?', 'A. 760 tot 780mm', 'B. 780 tot 800mm', 'C. 800 tot 820mm', 'C'),
(22, 'MC', 'Geography', 'Welke brug in Rotterdam heeft de volgende bijnaam: De zwaan.', 'A. De Willemsbrug', 'B. De Erasmusbrug', 'C. De van Briennenoordbrug', 'B'),
(23, 'MC', 'Geography', 'Rotterdam is de hoofdstad van Nederland.', 'A. Waar', 'B. Niet Waar', NULL, 'B'),
(24, 'MC', 'Geography', 'Wat is het oudste gebouw van Rotterdam?', 'A. Kerktoren Hillegondakerk', 'B. St. Laurenskerk', 'C. Stadhuis van Rotterdam', 'A'),
(25, 'MC', 'Geography', 'Rotterdam is de grootste stad van Nederland.', 'A. Waar', 'B. Niet Waar', NULL, 'A'),
(26, 'MC', 'Geography', 'Hoeveel mensen maken dagelijks gebruik van het openbaar vervoer in Rotterdam?', 'A. 800.00', 'B. 900.00', 'C. 1.000.000', 'C'),
(27, 'MC', 'Geography', 'Wat is de oudste brug van Rotterdam?', 'A. De Willemsbrug', 'B. De Koninginnebrug', 'C. De van Briennenoordbrug', 'B'),
(28, 'MC', 'Geography', 'Hoe heet de grootste rivier waar Rotterdam aan grenst', 'A. De Maas', 'B. De Rijn', 'C. De Waal', 'A'),
(29, 'MC', 'Geography', 'Hoeveel woningen zijn er ongeveer in Rotterdam?', 'A. 150.000', 'B. 300.000', 'C. 450.000', 'B'),
(30, 'MC', 'History', 'Wanneer is diergaarde Blijdorp geopend?', 'A. 1855', 'B. 1975', 'C. 1915', 'A'),
(31, 'MC', 'History', 'Waar dankt Rotterdam zijn naam aan?', 'A. Kooplieden hadden dit vroeger bedacht', 'B. Aan de rivier de rotte', 'C. Er was een dam aangelegd in de Maas', 'B'), 
(32, 'MC', 'History', 'Waar stond vroeger de wijk Katendrecht om bekend?', 'A. De beste bakker van de stad was daar gevestigd', 'B. De prostituees', 'C. De oudste beschermde boom van de stad staat door', 'B'), 
(33, 'MC', 'History', 'Wie is de nachtburgemeester van Rotterdam?', 'A. Ahmed Aboutaleb', 'B. Jules Deelder', 'C. Willer Alexander', 'B'),
(34, 'MC', 'History', 'In welk jaar heeft Rotterdam stadsrechten gekregen?', 'A. 1250', 'B. 1340', 'C. 1590', 'B'),
(35, 'MC', 'History', 'Wat is het enigste overgebleven middeleeuws gebouw in de binnenstad van Rotterdam?', 'A. De oude haven', 'B. VOC magazijn', 'C. St. Laurenskerk', 'C'),
(36, 'MC', 'History', 'Wat was tijdens de Wereldoorlog de enige weg naar het centrum die de Duitsers probeerden te bereiken?', 'A. De nieuwe Binnenweg', 'B. Maasbrug', 'C. Koninginnenbrug', 'B'), 
(37, 'MC', 'History', 'Wat is de officiele naam van de koopgoot?', 'A. De ondergrondse winkelstraat', 'B. Beurstraverse', 'C. Gewoon de koopgoot', 'B'),
(38, 'MC', 'History', 'Na 1872 is de stad Rotterdam snel groot geworden, Pieter Caland had een plan om Rotterdam met de zee te verbinden. Hoe noemde hij die verbinding?', 'A. De Nieuwe Waterweg', 'B. De Maas zeeverbinding', 'C. Het Nieuwe Water kanaal', 'A'),
(39, 'MC', 'History', 'Door welke architect(en) is de Euromast ontworpen?', 'A. Maaskant', 'B. Brinkman en van der Vlugt', 'C. Koolhaas', 'A'), 
(40, 'MC', 'History', 'Rotterdam was tot 1870 een opslag haven, welke producten werden er onder ander opgeslagen?', 'A. Suiker', 'B. Wol', 'C. Cacao', 'A'),
(41, 'MC', 'History', 'Welk gebouw (gebouwd in 1957) stond symbool voor de wederopbouw van de stad?', 'A. De Bijenkorf', 'B. De Kubuswoningen', 'C. The Red Apple', 'A'),
(42, 'MC', 'History', 'Hoeveel joden woonden er in Rotterdam voor de Tweede Wereldoorlog?', 'A. Ca. 5000', 'B. Ca. 8000', 'C. Ca. 12000', 'B'),
(43, 'MC', 'History', 'Hoe heette de haven van Rotterdam oorspronkelijk tijdens zijn ontstaan?', 'A. Waalhaven', 'B. De maashaven', 'C. Europoort', 'A'), 
(44, 'MC', 'History', 'Was de eerste metrolijn in Nederland in Rotterdam geopend?', 'A. Waar', 'B. Niet Waar', NULL, 'A'),
(45, 'OPEN', 'History', 'In welk voormalig hoofdkantoor is Hotel New York gevestigd?', NULL, NULL, NULL, 'holland amerika lijn'),
(46, 'OPEN', 'History', 'Welke hoogste kantoorgebouw was toen de eerste van Europa staat in Rotterdam?', NULL, NULL, NULL, 'het witte huis'),
(47, 'OPEN', 'History', 'Hoe heette de trans-Atlantische verbinding die vertrok vanaf Rotterdam naar Amerika?', NULL, NULL, NULL, 'holland amerika lijn'),
(48, 'OPEN', 'History', 'Hoe heet het schip dat in dienst was van de Holland Amerika Lijn?', NULL, NULL, NULL, 'ss rotterdam, de rotterdam, rotterdam'),
(49, 'OPEN', 'History', 'Wat is de grootste politieke partij van Rotterdam?', NULL, NULL, NULL, 'leefbaar rotterdam'),
(50, 'OPEN', 'History', 'Welke politicus uit Rotterdam werd vermoord in 2002?', NULL, NULL, NULL, 'pim fortuyn'),
(51, 'OPEN', 'History', 'Hoe heet het beeld dat Ossip Zadkine ontwierp naar aanleiding van het bombardement in Rotterdam? het is onthuld in 1953 en staat aan de Leuvenshaven naast het Maritiem Museum.', NULL, NULL, NULL, 'de verwoeste stad'),
(52, 'OPEN', 'History', 'Wat was Erasmus?', NULL, NULL, NULL, 'filosoof, humanist, auteur, priester'),
(53, 'OPEN', 'History', 'Wat zijn de twee bekendste bruggen in Rotterdam?', NULL, NULL, NULL, 'willemsbrug en erasmusbrug'),
(54, 'OPEN', 'History', 'Hoe heette het Loods in het havengebied dat in 1942 als verzamelpunt voor de deportatie van de Joodse inwoners?', NULL, NULL, NULL, 'loods24'),
(55, 'OPEN', 'History', 'Hoe lang duurde de Tweede Wereldoorlog in Nederland?', NULL, NULL, NULL, '5 jaar(1940 à 1945)'),
(56, 'OPEN', 'History', 'Welke gorilla ontsnapte er in 2007 uit de Diergaarde Blijdorp?', NULL, NULL, NULL, 'bokito'),
(57, 'OPEN', 'History', 'Welke openbaar vervoersmiddelen heb je in Rotterdam (noem er 5)?', NULL, NULL, NULL, 'bus, tram, metro, trein, waterbus'),
(58, 'OPEN', 'History', 'Wat is de bekendste Rotterdamse krant?', NULL, NULL, NULL, 'nrc'),
(59, 'OPEN', 'History', 'Waar staat de afkorting van de krant NRC voor?', NULL, NULL, NULL, 'nieuwe rotterdamse courant'),
(60, 'MC', 'Entertainment', 'Welk van de volgende winkels is niet rond de koopgoot?', 'A. H&M', 'B. Media Markt', 'C. The String', 'B'), 
(61, 'MC', 'Entertainment', 'Welk van de volgende restaurantboten in Rotterdam bestaat niet?', 'A. De Zwanenboot', 'B. De Pannenkoekenboot', 'C. De Berenboot', 'A'),
(62, 'MC', 'Entertainment', 'Welke van de volgende Pathé bioscopen is niet in Rotterdam?', 'A. De Kuip', 'B. De Kroon', 'C. Schouwburgplein', 'B'),
(63, 'MC', 'Entertainment', 'Voor welkvervoer middel is er geen tour beschikbaar in Rotterdam?', 'A. Segway', 'B. Boot', 'C. Auto', 'C'),
(64, 'MC', 'Entertainment', 'In welke bioscoop vindt het Wildlife film festival plaats?', 'A. Cinerama', 'B. Pathé de Kuip', 'C. Pathe Schouwburgplein', 'A'),
(65, 'MC', 'Entertainment', 'Voor welk Museum staat het monument van Zadkine genaamd de verwoeste stad?', 'A. Havenmuseum', 'B. Mariniersmuseum', 'C. Maritiem museum', 'C'),
(66, 'MC', 'Entertainment', 'Waar kan je niet terecht om te gaan zwemmen?', 'A. Hoek van Holland', 'B. Euromast park', 'C. Plaswijkpark', 'B'),
(67, 'MC', 'Entertainment', 'Waar geeft Rotterdam Tours onder andere rondleidingen?', 'A. De Euromast', 'B. Museumplein', 'C. De Markthal', 'C'),
(68, 'OPEN', 'Entertainment', 'Wat is de bekendste dierentuin in Rotterdam?', NULL, NULL, NULL, 'diergaarde blijdorp'),
(69, 'OPEN', 'Entertainment', 'Wat is de bekendste plek in Rotterdam waar je terecht kan voor concerten en evenementen?', NULL, NULL, NULL, 'rotterdam ahoy'),
(70, 'OPEN', 'Entertainment', 'Welke concertzaal bevindt zich bij Schouwburgplein?',NULL , NULL, NULL, 'de doelen'),
(71, 'OPEN', 'Entertainment', 'Met welke boot kun je rondvaren bij de Erasmusbrug', NULL, NULL, NULL, 'de spido'),
(72, 'OPEN', 'Entertainment', 'Welk kunstwerk wordt ook wel de Nederlandse versie van de sixtijnse kapel genoemd', NULL, NULL, NULL, 'de markthal'),
(73, 'OPEN', 'Entertainment', 'Wat is de populairste straat in Rotterdam om uit te gaan', NULL, NULL, NULL, 'witte de withstraat'),
(74, 'OPEN', 'Entertainment', 'Bij welke brug in Rotterdam vindt “het nationale vuurwerk” plaats', NULL, NULL, NULL, 'erasmusbrug'),
(75, 'OPEN', 'Entertainment', 'Bij welk station is het start punt van de Rotterdam street art route', NULL, NULL, NULL, 'centraal station'),
(76, 'OPEN', 'Entertainment', 'Hoe heet het theater dat zich naast Pathe schouwburg bevindt', NULL, NULL, NULL, 'rotterdam schouwburg'),
(77, 'OPEN', 'Entertainment', 'Bij welke gaven bevindt zich heet drijvend paviljoen', NULL, NULL, NULL, 'rotterdamse rijnhaven'),
(78, 'OPEN', 'Entertainment', 'Hoe heet het grootste film festival in Rotterdam', NULL, NULL, NULL, 'het internationaal film festival'),
(79, 'OPEN', 'Entertainment', 'In welke maand vinden de wereldhavendagen plaats', NULl, NULL, NULL, 'september'),
(80, 'OPEN', 'Entertainment', 'Welk festival in Rotterdam viert seksuele diversiteit', NULL, NULL, NULL, 'rotterdam pride'),
(81, 'OPEN', 'Entertainment', 'Hoe heet het evenement waarbij zombies door de binnenstad van Rotterdam lopen', NULL, NULL, NULL, 'rotterdam zombie walk'),
(82, 'MC', 'Entertainment', 'Welk van de volgende bioscopen is het oudst', 'A. Cinerama', 'B. Pathe de kuip', 'C. Lantaren-venster', 'C'),
(83, 'MC', 'Entertainment', 'Hoe heet de culturele en culinaire ontdekkingstocht door Rotterdam', 'A. Drive & Eat', 'B. Bicycle Diner', 'C. Bike & Bite', 'B'),
(84, 'MC', 'Entertainment', 'Wat is de bekendste escape room in Rotterdam', 'A. Rdam escape', 'B. Escape010', 'C. Room Escape', 'B'),
(85, 'MC', 'Entertainment', 'Welke bar in Rotterdam werd in 2009 de beste bar ter wereld benoemd', 'A. De Witte Aap', 'B. Het NRC', 'C. Cafe de beurs', 'A'),
(86, 'MC', 'Entertainment', 'Op welk Plein vindt jaarlijks het najaar kermis Rotterdam plaats', 'A. Mullepier', 'B. Pier 80', 'C. Schouwburgplein', 'A'),
(87, 'MC', 'Entertainment', 'Welke landen kun je behalve Nederland ook in miniwereld Rotterdam zien', 'A. Luxemburg en Belgie', 'B. Duitsland en Belgie', 'C. Duitsland en Frankrijk', 'A'),
(88, 'OPEN', 'Sport', 'Bij welke sport gebruik je een net om de bal in het doel te gooien', NULL, NUll, NULL, 'lacrosse'),
(89, 'OPEN', 'Sport', 'Welke veld sport wordt het meest bespeelt in Rotterdam', NULL, NULL, NULl, 'voetbal'),
(90, 'OPEN', 'Sport', 'Hoe heet de trainer van de Nederlandse waterpolo dames die goud won in 2008 op de Olympische spelen', NULL, NUll, NULL, 'robin van galen'),
(91, 'OPEN', 'Sport', 'Hoe noemt men het als je een bal in de basket slaat', NULl, NULL, NULL, 'dunken'),
(92, 'OPEN', 'Sport', 'Er is een Rotterdamse basketbalclub die op het hoogste niveau speelt, hoe heet deze club', NULL, NULl, NULL, 'forward lease rotterdam'),
(93, 'OPEN', 'Sport', 'Van welke lijn moet een speler bij basketschieten voor een driepunter', NULl, NULl, NULL, 'driepuntslijn'),
(94, 'OPEN', 'Sport', 'Wat noemt men een ace bij tennis en volleybal', NUll, NULL, NULL, 'een niet door de tegenstander aangeraakte serveerslag'),
(95, 'OPEN', 'Sport', 'Hoe heet het sportcentrum naast de kuip', NULL, NULL, NULL, 'topsportcentrum rotterdam'),
(96, 'OPEN', 'Sport', 'Hoeveel punten levert een vrijeworp op in basketbal', NULL, NULl, NULL, '1 punt'),
(97, 'OPEN', 'Sport', 'Welke voetbalclub heeft de Europacup 1 gewonnen', NULL, NULL, NULL, 'feyenoord'),
(98, 'OPEN', 'Sport', 'Wat is het grootste eendaagse sport evenement van Rotterdam', NULl, NULL, NULL, 'marathon van rotterdam'), 
(99, 'OPEN', 'Sport', 'Wat zijn de 3 Professionele voetbalclubs uit Rotterdam', NULL, NULL, NULL, 'feyenoord, sparta, excelsior'),
(100,'OPEN', 'Sport', 'Hoe heet de Formule 1 race in Rotterdam', NULl, NULL, NULL, 'city racing rotterdam'),
(101,'OPEN', 'Sport', 'Hoe heet de stadion van de honkbalclub Neptunes', NULL, NULL, NULL, 'neptunes familiestadion'),
(102,'OPEN', 'Sport', 'Hoe lang is de NN marathon van Rotterdam', NULL, NULL, NULL, '42Km'),
(103,'MC', 'Sport', 'Welke olympier groeide op in Rotterdam', 'A. Dorian van Rijsselberghe', 'B. Marhinde Verkerk', 'C. Edith Bosch', 'B'),
(104,'MC', 'Sport', 'Wat is een hockeyclub uit Rotterdam', 'A. HVG', 'B. Focus', 'C. HC Rotterdam', 'A'),
(105,'OPEN', 'Sport', 'Op welke baan vond het WK roeien in 2016 plaats', NULl, NULL, NULL, 'willem alexander baan'),
(106,'MC', 'Sport', 'In welk jaar is de honkbalclub Neptunes opgericht', 'A. 1850', 'B. 1875', 'C. 1900', 'C'),
(107,'MC', 'Sport', 'Op welke positie speelde Coen Moulijn voor Feyenoord en het Nederlands elftal', 'A. Rechtsbuiten', 'B. Linksback', 'C. Linksbuiten', 'C'),
(108,'MC', 'Sport', 'Hoeveel spelers staan per team op het veld bij lacrosse', 'A. 9', 'B. 10', 'C. 11', 'C'),
(109,'MC', 'Sport', 'Een honkbal is groter dan een softbal', 'A. Waar', 'B. Niet waar', NULL, 'B'),
(110,'MC', 'Sport', 'Welke manier van sport word het meest beoefend in Rotterdam', 'A. Fitness', 'B. Voetbal', 'C. Basketbal', 'A'),
(111,'MC', 'Sport', 'Hoeveel mensen staan er achter de slagman bij honkbal', 'A. 1', 'B. 2',  'C. 3', 'B' ),
(112,'OPEN', 'Sport', 'Welk tennis toernooi word er elk jaar in Ahoy gehouden', NULL, NULL, NULL, 'abn amro world tennis tournament'),
(113,'OPEN', 'Sport', 'Voor welke 3 sporten is de Willem Alexander baan het meest geschikt', NULL, NULL, NULL, 'watersporten, wielrennen en hardlopen'),
(114,'OPEN', 'Sport', 'Hoe heet het Stadion van Sparta', NULL, NULL, NULL, 'het kasteel'),
(115,'MC', 'Sport', 'Een speler is buiten spel als', 'A. Hij zich veder van het doel bevindt als de keeper', 'B. Zich dichter bij de doellijn van de tegenstander bevindt dan de bal en de voorlaatste tegenstander', 'C. Zich buiten de lijn van het veld bevindt en de bal in het spel is', 'B');