INSERT INTO QnA(Question_ID, Question_type, Question_Catagory, Question, Answer1, Answer2, Answer3, correct_answer, Correct_answer2, Correct_answer3, Correct_answer4)
VALUES 
(1, 'OPEN', 'Geography', 'Hoe hoog is de Euromast?', NULL, NULL, NULL, '185 meter', '185', '185m', NULL),
(2, 'OPEN', 'Geography', 'Welke stad is groter dan Rotterdam?', NULL, NULL, NULL, 'geen', 'er is geen grotere stad', 'geen enkele', NULL), 
(3, 'OPEN', 'Geography', 'Wat is de hoogste brug van Rotterdam?', NULL, NULL, NULL, 'de erasmusbrug', 'erasmusbrug', NULL, NULL), 
(4, 'OPEN', 'Geography', 'Hoe groot is Rotterdam, inclusief wateren?, ', NULL, NULL, NULL, '320 km2', '320', '320km2', NULL),
(5, 'OPEN', 'Geography', 'Hoe heet de berg die in Rotterdam ligt?', NULL, NULL, NULL, 'rotterdam heeft geen bergen', 'er zijn geen bergen', 'bestaat niet', NULL),
(6, 'OPEN', 'Geography', 'Welke klimaat heerst er in Rotterdam?', NULL, NULL, NULL, 'gematigd zeeklimaat', 'zeeklimaat', 'zee', NULL),
(7, 'OPEN', 'Geography', 'Wat is de oudste deelgemeente van Rotterdam?', NULL, NULL, NULL, 'rotterdam noord', 'noord', 'noord rotterdam' , NULL), 
(8, 'OPEN', 'Geography', 'Hoe heet het monument dat op een kerstboom had moeten lijken.', NULL, NULL, NULL, 'santa claus', 'kabouter buttplug', NULL, NULL),
(9, 'OPEN', 'Geography', 'Welke snel-of-autoweg ligt er langs of door Rotterdam.', NULL, NULL, NULL, 'a13', 'a15', 'a16', 'a20'),
(10,'OPEN', 'Geography', 'Hoe heten de bekendste huizen van Rotterdam?', NULL, NULL, NULL, 'de kubuswoningen', 'kubuswoningen', 'kubuswoning', NULL),
(11,'OPEN', 'Geography', 'Wat is het hoogste gebouw van Rotterdam?', NULL, NULL, NULL, 'de maastoren', 'maastoren', NULL, NULL), 
(12,'OPEN', 'Geography', 'Hoeveel autos staan er ongeveer geregistreerd in Rotterdam?', NULL, NULL, NULL, 'ongeveer 200000 autos', '200000', '200000 autos', NULL),
(13,'OPEN', 'Geography', 'Hoeveel mensen wonen er ongeveer in Rotterdam?', NULL, NULL, NULL, 'ongeveer 610000', '610000', '610000 mensen', '600000'),
(14,'OPEN', 'Geography', 'Hoeveel winkels telt Rotterdam?', NULL, NULL, NULL, '9500', '9455 winkels', '9455', '9400'), 
(15, 'MC', 'Geography', 'Wat is het belangrijkste vervoersmiddel in Rotterdam?', 'A. Metro', 'B. Auto', 'C. Fiets', 'A', NULL, NULL, NULL),
(16, 'MC', 'Geography', 'De haven van Rotterdam is grootste haven van Nederland.', 'A. Waar', 'B. Niet Waar', NULL, 'A', NULL, NULL, NULL),
(17, 'MC', 'Geography', 'Hoe word Rotterdam ook wel genoemd?', 'A. Stad der wonderen', 'B. Stad der steden', 'C. Haven stad', 'C', NULL, NULL, NULL),
(18, 'MC', 'Geography', 'In welke provincie ligt Rotterdam?', 'A. Groningen', 'B. Zuid-Holland', 'C. Noord-Holland', 'B', NULL, NULL, NULL),
(19, 'MC', 'Geography', 'Rotterdam is de hoofdstad van Zuid-Holland.', 'A. Waar', 'B. Niet Waar', NULL, 'B', NULL, NULL, NULL),
(20, 'MC', 'Geography', 'Hoeveel regen valt er gemiddeld per jaar in Rotterdam?', 'A. 760 tot 780mm', 'B. 780 tot 800mm', 'C. 800 tot 820mm', 'C', NULL, NULL, NULL),
(21, 'MC', 'Geography', 'Welke brug in Rotterdam heeft de volgende bijnaam: De zwaan.', 'A. De Willemsbrug', 'B. De Erasmusbrug', 'C. De van Briennenoordbrug', 'B', NULL, NULL, NULL),
(22, 'MC', 'Geography', 'Rotterdam is de hoofdstad van Nederland.', 'A. Waar', 'B. Niet Waar', NULL, 'B', NULL, NULL, NULL),
(23, 'MC', 'Geography', 'Wat is het oudste gebouw van Rotterdam?', 'A. Kerktoren Hillegondakerk', 'B. St. Laurenskerk', 'C. Stadhuis van Rotterdam', 'A', NULL, NULL, NULL),
(24, 'MC', 'Geography', 'Rotterdam is de grootste stad van Nederland.', 'A. Waar', 'B. Niet Waar', NULL, 'A', NULL, NULL, NULL),
(25, 'MC', 'Geography', 'Hoeveel mensen maken dagelijks gebruik van het openbaar vervoer in Rotterdam?', 'A. 800.00', 'B. 900.00', 'C. 1.000.000', 'C', NULL, NULL, NULL),
(26, 'MC', 'Geography', 'Wat is de oudste brug van Rotterdam?', 'A. De Willemsbrug', 'B. De Koninginnebrug', 'C. De van Briennenoordbrug', 'B', NULL, NULL, NULL),
(27, 'MC', 'Geography', 'Hoe heet de grootste rivier waar Rotterdam aan grenst', 'A. De Maas', 'B. De Rijn', 'C. De Waal', 'A', NULL, NULL, NULL),
(28, 'MC', 'Geography', 'Hoeveel woningen zijn er ongeveer in Rotterdam?', 'A. 150.000', 'B. 300.000', 'C. 450.000', 'B', NULL, NULL, NULL),
(29, 'MC', 'History', 'Wanneer is diergaarde Blijdorp geopend?', 'A. 1855', 'B. 1975', 'C. 1915', 'A', NULL, NULL, NULL),
(30, 'MC', 'History', 'Waar dankt Rotterdam zijn naam aan?', 'A. Kooplieden hadden dit vroeger bedacht', 'B. Aan de rivier de rotte', 'C. Er was een dam aangelegd in de Maas', 'B', NULL, NULL, NULL), 
(31, 'MC', 'History', 'Waar stond vroeger de wijk Katendrecht om bekend?', 'A. De beste bakker van de stad was daar gevestigd', 'B. De prostituees', 'C. De oudste beschermde boom van de stad staat door', 'B', NULL, NULL, NULL), 
(32, 'MC', 'History', 'Wie is de nachtburgemeester van Rotterdam?', 'A. Ahmed Aboutaleb', 'B. Jules Deelder', 'C. Willer Alexander', 'B', NULL, NULL, NULL),
(33, 'MC', 'History', 'In welk jaar heeft Rotterdam stadsrechten gekregen?', 'A. 1250', 'B. 1340', 'C. 1590', 'B', NULL, NULL, NULL),
(34, 'MC', 'History', 'Wat is het enigste overgebleven middeleeuws gebouw in de binnenstad van Rotterdam?', 'A. De oude haven', 'B. VOC magazijn', 'C. St. Laurenskerk', 'C', NULL, NULL, NULL),
(35, 'MC', 'History', 'Wat was tijdens de Wereldoorlog de enige weg naar het centrum die de Duitsers probeerden te bereiken?', 'A. De nieuwe Binnenweg', 'B. Maasbrug', 'C. Koninginnenbrug', 'B', NULL, NULL, NULL), 
(36, 'MC', 'History', 'Wat is de officiele naam van de koopgoot?', 'A. De ondergrondse winkelstraat', 'B. Beurstraverse', 'C. Gewoon de koopgoot', 'B', NULL, NULL, NULL),
(37, 'MC', 'History', 'Na 1872 is de stad Rotterdam snel groot geworden, Pieter Caland had een plan om Rotterdam met de zee te verbinden. Hoe noemde hij die verbinding?', 'A. De Nieuwe Waterweg', 'B. De Maas zeeverbinding', 'C. Het Nieuwe Water kanaal', 'A', NULL, NULL, NULL),
(38, 'MC', 'History', 'Door welke architect(en) is de Euromast ontworpen?', 'A. Maaskant', 'B. Brinkman en van der Vlugt', 'C. Koolhaas', 'A', NULL, NULL, NULL), 
(39, 'MC', 'History', 'Rotterdam was tot 1870 een opslag haven, welke producten werden er onder ander opgeslagen?', 'A. Suiker', 'B. Wol', 'C. Cacao', 'A', NULL, NULL, NULL),
(40, 'MC', 'History', 'Welk gebouw (gebouwd in 1957) stond symbool voor de wederopbouw van de stad?', 'A. De Bijenkorf', 'B. De Kubuswoningen', 'C. The Red Apple', 'A', NULL, NULL, NULL),
(41, 'MC', 'History', 'Hoeveel joden woonden er in Rotterdam voor de Tweede Wereldoorlog?', 'A. Ca. 5000', 'B. Ca. 8000', 'C. Ca. 12000', 'B', NULL, NULL, NULL),
(42, 'MC', 'History', 'Hoe heette de haven van Rotterdam oorspronkelijk tijdens zijn ontstaan?', 'A. Waalhaven', 'B. De maashaven', 'C. Europoort', 'A', NULL, NULL, NULL), 
(43, 'MC', 'History', 'Was de eerste metrolijn in Nederland in Rotterdam geopend?', 'A. Waar', 'B. Niet Waar', NULL, 'A', NULL, NULL, NULL),
(44, 'OPEN', 'History', 'In welk voormalig hoofdkantoor is Hotel New York gevestigd?', NULL, NULL, NULL, 'holland amerika lijn', 'amerika lijn', 'hal', NULL),
(45, 'OPEN', 'History', 'Welk kantoorgebouw was een tijd lang het hoogste toen het werd geopend', NULL, NULL, NULL, 'het witte huis', 'witte huis', NULL, NULL),
(46, 'OPEN', 'History', 'Hoe heette de trans-Atlantische verbinding die vertrok vanaf Rotterdam naar Amerika?', NULL, NULL, NULL, 'holland amerika lijn', 'amerika lijn', NULL, NULL),
(47, 'OPEN', 'History', 'Hoe heet het schip dat in dienst was van de Holland Amerika Lijn?', NULL, NULL, NULL, 'ss rotterdam', 'de rotterdam', 'rotterdam', NULL),
(48, 'OPEN', 'History', 'Wat is de grootste politieke partij van Rotterdam?', NULL, NULL, NULL, 'leefbaar rotterdam', 'leefbaar', NULL, NULL),
(49, 'OPEN', 'History', 'Welke politicus uit Rotterdam werd vermoord in 2002?', NULL, NULL, NULL, 'pim fortuyn', 'pim', 'fortuyn', NULL),
(50, 'OPEN', 'History', 'Hoe heet het beeld dat Ossip Zadkine ontwierp naar aanleiding van het bombardement in Rotterdam? het is onthuld in 1953 en staat aan de Leuvenshaven naast het Maritiem Museum.', NULL, NULL, NULL, 'de verwoeste stad', 'verwoeste stad', NULL, NULL),
(51, 'OPEN', 'History', 'Wat was Erasmus?', NULL, NULL, NULL, 'filosoof', 'humanist', 'auteur', 'priester'),
(52, 'OPEN', 'History', 'noem een van de twee bekendste bruggen in Rotterdam?', NULL, NULL, NULL, 'willemsbrug', 'erasmusbrug', 'willems brug', 'erasmus brug'),
(53, 'OPEN', 'History', 'Hoe heette het Loods in het havengebied dat in 1942 als verzamelpunt voor de deportatie van de Joodse inwoners?', NULL, NULL, NULL, 'loods24', 'loods 24', NULL, NULL),
(54, 'OPEN', 'History', 'Hoe lang duurde de Tweede Wereldoorlog in Nederland?', NULL, NULL, NULL, '5 jaar', '5', '5 jaren', NULL),
(55, 'OPEN', 'History', 'Welke gorilla ontsnapte er in 2007 uit de Diergaarde Blijdorp?', NULL, NULL, NULL, 'bokito', NULL, NULL, NULL),
(56, 'OPEN', 'History', 'Wat is de bekendste Rotterdamse krant?', NULL, NULL, NULL, 'nrc', 'nrc handelsblad', 'het nrc', 'het nrc handelsblad'),
(57, 'OPEN', 'History', 'Waar staat de afkorting van de krant NRC voor?', NULL, NULL, NULL, 'nieuwe rotterdamse courant', 'nieuw rotterdams courant', NULL, NULL),
(58, 'MC', 'Entertainment', 'Welk van de volgende winkels is niet rond de koopgoot?', 'A. H&M', 'B. Media Markt', 'C. The String', 'B', NULL, NULL, NULL), 
(59, 'MC', 'Entertainment', 'Welk van de volgende restaurantboten in Rotterdam bestaat niet?', 'A. De Zwanenboot', 'B. De Pannenkoekenboot', 'C. De Berenboot', 'A', NULL, NULL, NULL),
(60, 'MC', 'Entertainment', 'Welke van de volgende Pathé bioscopen is niet in Rotterdam?', 'A. De Kuip', 'B. De Kroon', 'C. Schouwburgplein', 'B', NULL, NULL, NULL),
(61, 'MC', 'Entertainment', 'Voor welkvervoer middel is er geen tour beschikbaar in Rotterdam?', 'A. Segway', 'B. Boot', 'C. Auto', 'C', NULL, NULL, NULL),
(62, 'MC', 'Entertainment', 'In welke bioscoop vindt het Wildlife film festival plaats?', 'A. Cinerama', 'B. Pathe de Kuip', 'C. Pathe Schouwburgplein', 'A', NULL, NULL, NULL),
(63, 'MC', 'Entertainment', 'Voor welk Museum staat het monument van Zadkine genaamd de verwoeste stad?', 'A. Havenmuseum', 'B. Mariniersmuseum', 'C. Maritiem museum', 'C', NULL, NULL, NULL),
(64, 'MC', 'Entertainment', 'Waar kan je niet terecht om te gaan zwemmen?', 'A. Hoek van Holland', 'B. Euromast park', 'C. Plaswijkpark', 'B', NULL, NULL, NULL),
(65, 'MC', 'Entertainment', 'Waar geeft Rotterdam Tours onder andere rondleidingen?', 'A. De Euromast', 'B. Museumplein', 'C. De Markthal', 'C', NULL, NULL, NULL),
(66, 'OPEN', 'Entertainment', 'Wat is de bekendste dierentuin in Rotterdam?', NULL, NULL, NULL, 'diergaarde blijdorp', 'blijdorp', 'dierentuin blijdorp', NULL),
(67, 'OPEN', 'Entertainment', 'Wat is de bekendste plek in Rotterdam waar je terecht kan voor concerten en evenementen?', NULL, NULL, NULL, 'rotterdam ahoy', 'ahoy', 'ahoy rotterdam', NULL),
(68, 'OPEN', 'Entertainment', 'Welke concertzaal bevindt zich bij Schouwburgplein?',NULL , NULL, NULL, 'de doelen', 'doelen', NULL, NULL),
(69, 'OPEN', 'Entertainment', 'Met welke boot kun je rondvaren bij de Erasmusbrug', NULL, NULL, NULL, 'de spido', 'spido', NULL, NULL),
(70, 'OPEN', 'Entertainment', 'Welk kunstwerk wordt ook wel de Nederlandse versie van de sixtijnse kapel genoemd', NULL, NULL, NULL, 'de markthal', 'markthal', NULL, NULL),
(71, 'OPEN', 'Entertainment', 'Wat is de populairste straat in Rotterdam om uit te gaan', NULL, NULL, NULL, 'witte de withstraat', 'de withstraat', 'witte de with straat', 'witte de witstraat'),
(72, 'OPEN', 'Entertainment', 'Bij welke brug in Rotterdam vindt “het nationale vuurwerk” plaats', NULL, NULL, NULL, 'erasmusbrug', 'de erasmusbrug', 'erasmus brug', NULL),
(73, 'OPEN', 'Entertainment', 'Bij welk station is het start punt van de Rotterdam street art route', NULL, NULL, NULL, 'centraal station', NULL, NULL, NULL),
(74, 'OPEN', 'Entertainment', 'Hoe heet het theater dat zich naast Pathe schouwburg bevindt', NULL, NULL, NULL, 'rotterdam schouwburg', 'de schouwburg', 'schouwburg', NULL),
(75, 'OPEN', 'Entertainment', 'Bij welke haven bevindt zich het drijvend paviljoen', NULL, NULL, NULL, 'rotterdamse rijnhaven', 'rijnhaven', 'de rijnhaven', NULL),
(76, 'OPEN', 'Entertainment', 'In welke maand vinden de wereldhavendagen plaats', NULl, NULL, NULL, 'september', '9de maand', 'de 9de maand', '09'),
(77, 'OPEN', 'Entertainment', 'Welk festival in Rotterdam viert seksuele diversiteit', NULL, NULL, NULL, 'rotterdam pride', 'pride', 'het festival rotterdam pride', NULL),
(78, 'OPEN', 'Entertainment', 'Hoe heet het evenement waarbij zombies door de binnenstad van Rotterdam lopen', NULL, NULL, NULL, 'rotterdam zombie walk', 'zombie walk', 'de zombie walk', 'zombiewalk'),
(79, 'MC', 'Entertainment', 'Welk van de volgende bioscopen is het oudst', 'A. Cinerama', 'B. Pathe de kuip', 'C. Lantaren-venster', 'C', NULL, NULL, NULL),
(80, 'MC', 'Entertainment', 'Hoe heet de culturele en culinaire ontdekkingstocht door Rotterdam', 'A. Drive & Eat', 'B. Bicycle Diner', 'C. Bike & Bite', 'B', NULL, NULL, NULL),
(81, 'MC', 'Entertainment', 'Wat is de bekendste escape room in Rotterdam', 'A. Rdam escape', 'B. Escape010', 'C. Room Escape', 'B', NULL, NULL, NULL),
(82, 'MC', 'Entertainment', 'Welke bar in Rotterdam werd in 2009 de beste bar ter wereld benoemd', 'A. De Witte Aap', 'B. Het NRC', 'C. Cafe de beurs', 'A', NULL, NULL, NULL),
(83, 'MC', 'Entertainment', 'Op welk Plein vindt jaarlijks het najaar kermis Rotterdam plaats', 'A. Mullepier', 'B. Pier 80', 'C. Schouwburgplein', 'A', NULL, NULL, NULL),
(84, 'MC', 'Entertainment', 'Welke landen kun je behalve Nederland ook in miniwereld Rotterdam zien', 'A. Luxemburg en Belgie', 'B. Duitsland en Belgie', 'C. Duitsland en Frankrijk', 'A', NULL, NULL, NULL),
(85, 'OPEN', 'Sport', 'Bij welke sport gebruik je een net om de bal in het doel te gooien', NULL, NUll, NULL, 'lacrosse', NULL, NULL, NULL),
(86, 'OPEN', 'Sport', 'Welke veldsport wordt het meest bespeelt in Rotterdam', NULL, NULL, NULl, 'voetbal', NULL, NULL, NULL),
(87, 'OPEN', 'Sport', 'Hoe heet de trainer van de Nederlandse waterpolo dames die goud won in 2008 op de Olympische spelen', NULL, NUll, NULL, 'robin van galen', 'robin', 'van galen', NULL),
(88, 'OPEN', 'Sport', 'Hoe noemt men het als je een bal in de basket slaat', NULl, NULL, NULL, 'dunken', NULL, NULL, NULL),
(89, 'OPEN', 'Sport', 'Er is een Rotterdamse basketbalclub die op het hoogste niveau speelt, hoe heet deze club', NULL, NULl, NULL, 'forward lease rotterdam', 'forward lease', NULL, NULL),
(90, 'OPEN', 'Sport', 'Van welke lijn moet een speler bij basketschieten voor een driepunter', NULl, NULl, NULL, 'driepuntslijn', 'driepunts', 'driepunts lijn', NULL),
(91, 'OPEN', 'Sport', 'Hoe heet het sportcentrum naast de kuip', NULL, NULL, NULL, 'topsportcentrum rotterdam', 'topsportcentrum', 'topsport centrum', 'top sport centrum'),
(92, 'OPEN', 'Sport', 'Hoeveel punten levert een vrijeworp op in basketbal', NULL, NULl, NULL, '1 punt', '1', NULL, NULL),
(93, 'OPEN', 'Sport', 'Welke voetbalclub heeft de Europacup 1 gewonnen', NULL, NULL, NULL, 'feyenoord', NULL, NULL, NULL),
(94, 'OPEN', 'Sport', 'Wat is het grootste eendaagse sport evenement van Rotterdam', NULl, NULL, NULL, 'marathon van rotterdam', 'marathon', 'de marathon', 'rotterdamse marathon'), 
(95, 'OPEN', 'Sport', 'Noem een Professionele voetbalclub uit Rotterdam', NULL, NULL, NULL, 'feyenoord', 'sparta', 'excelsior', NULL),
(96,'OPEN', 'Sport', 'Hoe heet de Formule 1 race in Rotterdam', NULl, NULL, NULL, 'city racing rotterdam', 'city racing', 'cityracing', NULL),
(97,'OPEN', 'Sport', 'Hoe heet de stadion van de honkbalclub Neptunes', NULL, NULL, NULL, 'neptunes familiestadion', 'neptunes stadion', NULL, NULL),
(98,'OPEN', 'Sport', 'Hoe lang is de NN marathon van Rotterdam', NULL, NULL, NULL, '42km', '42', '42 km', NULL),
(99,'MC', 'Sport', 'Welke olympier groeide op in Rotterdam', 'A. Dorian van Rijsselberghe', 'B. Marhinde Verkerk', 'C. Edith Bosch', 'B', NULL, NULL, NULL),
(100,'MC', 'Sport', 'Wat is een hockeyclub uit Rotterdam', 'A. HVG', 'B. Focus', 'C. HC Rotterdam', 'A', NULL, NULL, NULL),
(101,'OPEN', 'Sport', 'Op welke baan vond het WK roeien in 2016 plaats', NULl, NULL, NULL, 'willem alexander baan', 'alexander baan', 'alexanderbaan', 'baan van willem alexander'),
(102,'MC', 'Sport', 'In welk jaar is de honkbalclub Neptunes opgericht', 'A. 1850', 'B. 1875', 'C. 1900', 'C', NULL, NULL, NULL),
(103,'MC', 'Sport', 'Op welke positie speelde Coen Moulijn voor Feyenoord en het Nederlands elftal', 'A. Rechtsbuiten', 'B. Linksback', 'C. Linksbuiten', 'C', NULL, NULL, NULL),
(104,'MC', 'Sport', 'Hoeveel spelers staan per team op het veld bij lacrosse', 'A. 9', 'B. 10', 'C. 11', 'C', NULL, NULL, NULL),
(105,'MC', 'Sport', 'Een honkbal is groter dan een softbal', 'A. Waar', 'B. Niet waar', NULL, 'B', NULL, NULL, NULL),
(106,'MC', 'Sport', 'Welke manier van sport word het meest beoefend in Rotterdam', 'A. Fitness', 'B. Voetbal', 'C. Basketbal', 'A', NULL, NULL, NULL),
(107,'MC', 'Sport', 'Hoeveel mensen staan er achter de slagman bij honkbal', 'A. 1', 'B. 2',  'C. 3', 'B' , NULL, NULL, NULL),
(108,'OPEN', 'Sport', 'Welk tennis toernooi word er elk jaar in Ahoy gehouden', NULL, NULL, NULL, 'rotterdam open', 'open', NULL, NULL),
(109,'OPEN', 'Sport', 'Voor welke sport is de Willem Alexander baan het meest geschikt', NULL, NULL, NULL, 'watersporten', 'wielrennen', 'hardlopen', NULL),
(110,'OPEN', 'Sport', 'Hoe heet het Stadion van Sparta', NULL, NULL, NULL, 'het kasteel', 'kasteel', NULL, NULL),
(111,'MC', 'Sport', 'Een speler is buiten spel als', 'A. Hij zich veder van het doel bevindt als de keeper', 'B. Zich dichter bij de doellijn van de tegenstander bevindt dan de bal en de voorlaatste tegenstander', 'C. Zich buiten de lijn van het veld bevindt en de bal in het spel is', 'B', NULL, NULL, NULL);
